version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/ArpitLT/gradle-tunnel-sample/compare/4d4b8d2ed1fe3d34d80132a4d2dff8003bb6ce9b...3421f569219bfbc6291ab5871bd25cb1131ea141
    - JVM_OPTS: -Xmx3200m
    - TERM: dumb
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    - run: gradle dependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - run: gradle test
workflows:
  version: 2
  workflow:
    jobs:
    - build